# This is the settings file for Buffet. 
#
# You are seeing this because you are running Buffet for the first time.
# Edit it to include relevant information about the project you are 
# testing. Save and quit when you're done.
#
# If you want to change settings later, run buffet --settings.

# The hosts that Buffet will test with.
hosts:
  - hostname1
  - hostname2
  - ...

# Details about the github repository we are testing. 
github:
  username: your-github-username
  token: your-token
  repository: name-of-testing-repo
  owner: owner-of-repository
repository: git@github.com:yourname/somerepo.git (full path to testing repo)

# Port should not be in use by any other application; neither should (port + 1).
port: 8990

# What framework are you using? Buffet takes an educated guess, but will use this
# as a fallback.
framework: rspec2 or rspec1

#If you use campfire, set this to true and fill out the details. 
use_campfire: false
campfire:
  username: username
  password: password
  subdomain: subdomain # subdomain.campfirenow.com
  room_name: name
