# The hosts that Buffet will test with.
hosts:
  - hostname1
  - hostname2
  - ...

# Details about the github repository we are testing.
repository: git@github.com:yourname/somerepo.git (full path to testing repo)

# Port should not be in use by any other application; neither should (port + 1).
port: 8990

# What framework are you using? Buffet takes an educated guess, but will use this
# as a fallback.
framework: rspec2 or rspec1
